//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entityEntities : DbContext
    {
        public entityEntities()
            : base("name=entityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tabla> tabla { get; set; }

        public System.Data.Entity.DbSet<crud.Models.TablaModel> TablaModels { get; set; }

        public System.Data.Entity.DbSet<crud.Models.TablaViewModel> TablaViewModels { get; set; }
    }
}
